# Generated by Django 2.2.11 on 2020-04-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
